[project]
dependencies = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
    "jupyter>=1.1.1",
    # "nglui>=3.7.1",
    # "pcg-skel>=1.1.0",
    # "pyvista[all]>=0.44.1",
]
description = "Add your description here"
name = "testbed"
readme = "README.md"
requires-python = ">=3.10,<3.13"
version = "0.1.0"
